library(collapse)

#-----Dialysis Facility - Listing by Facility-----
esrd <- readr::read_csv(
  file = fs::path("C:/Users/Andrew/Downloads/DFC_FACILITY.csv"),
  num_threads = 4L,
  col_types = readr::cols(
    `CMS Certification Number (CCN)`                                                                             = readr::col_character(),
    Network                                                                                                      = readr::col_integer(),
    `Facility Name`                                                                                              = readr::col_character(),
    `Five Star Date`                                                                                             = readr::col_character(),
    `Five Star`                                                                                                  = readr::col_double(),
    `Five Star Data Availability Code`                                                                           = readr::col_character(),
    `Address Line 1`                                                                                             = readr::col_character(),
    `Address Line 2`                                                                                             = readr::col_character(),
    `City/Town`                                                                                                  = readr::col_character(),
    State                                                                                                        = readr::col_character(),
    `ZIP Code`                                                                                                   = readr::col_character(),
    `County/Parish`                                                                                              = readr::col_character(),
    `Telephone Number`                                                                                           = readr::col_character(),
    `Profit or Non-Profit`                                                                                       = readr::col_character(),
    `Chain Owned`                                                                                                = readr::col_character(),
    `Chain Organization`                                                                                         = readr::col_character(),
    `Late Shift`                                                                                                 = readr::col_character(),
    `# of Dialysis Stations`                                                                                     = readr::col_double(),
    `Offers in-center hemodialysis`                                                                              = readr::col_character(),
    `Offers peritoneal dialysis`                                                                                 = readr::col_character(),
    `Offers home hemodialysis training`                                                                          = readr::col_character(),
    `Certification Date`                                                                                         = readr::col_character(),
    `Claims Date`                                                                                                = readr::col_character(),
    `EQRS Date`                                                                                                  = readr::col_character(),
    `SMR Date`                                                                                                   = readr::col_character(),
    `Patient Survival Category Text`                                                                             = readr::col_character(),
    `Patient Survival data availability code`                                                                    = readr::col_character(),
    `Number of Patients included in survival summary`                                                            = readr::col_double(),
    `Mortality Rate (Facility)`                                                                                  = readr::col_double(),
    `Mortality Rate: Upper Confidence Limit (97.5%)`                                                             = readr::col_double(),
    `Mortality Rate: Lower Confidence Limit (2.5%)`                                                              = readr::col_double(),
    `SHR Date`                                                                                                   = readr::col_character(),
    `Patient hospitalization category text`                                                                      = readr::col_character(),
    `Patient Hospitalization data availability Code`                                                             = readr::col_character(),
    `Number of patients included in hospitalization summary`                                                     = readr::col_double(),
    `Hospitalization Rate (Facility)`                                                                            = readr::col_double(),
    `Hospitalization Rate: Upper Confidence Limit (97.5%)`                                                       = readr::col_double(),
    `Hospitalization Rate: Lower Confidence Limit (2.5%)`                                                        = readr::col_double(),
    `SRR Date`                                                                                                   = readr::col_character(),
    `Patient Hospital Readmission Category`                                                                      = readr::col_character(),
    `Patient Hospital Readmission data availability Code`                                                        = readr::col_character(),
    `Number of hospitalizations included in hospital readmission summary`                                        = readr::col_double(),
    `Readmission Rate (Facility)`                                                                                = readr::col_double(),
    `Readmission Rate: Upper Confidence Limit (97.5%)`                                                           = readr::col_double(),
    `Readmission Rate: Lower Confidence Limit (2.5%)`                                                            = readr::col_double(),
    `STrR Date`                                                                                                  = readr::col_character(),
    `Patient Transfusion category text`                                                                          = readr::col_character(),
    `Patient Transfusion data availability Code`                                                                 = readr::col_character(),
    `Number of patients included in the transfusion summary`                                                     = readr::col_double(),
    `Transfusion Rate (Facility)`                                                                                = readr::col_double(),
    `Transfusion Rate: Upper Confidence Limit (97.5%)`                                                           = readr::col_double(),
    `Transfusion Rate: Lower Confidence Limit (2.5%)`                                                            = readr::col_double(),
    `SWR Date`                                                                                                   = readr::col_character(),
    `SWR category text`                                                                                          = readr::col_character(),
    `Patient transplant waitlist data availability code`                                                         = readr::col_character(),
    `Number of patients in this facility for SWR`                                                                = readr::col_double(),
    `Standardized First Kidney Transplant Waitlist Ratio`                                                        = readr::col_double(),
    `95% C.I. (upper limit) for SWR`                                                                             = readr::col_double(),
    `95% C.I. (lower limit) for SWR`                                                                             = readr::col_double(),
    `PPPW category text`                                                                                         = readr::col_character(),
    `Patient prevalent transplant waitlist data availability code`                                               = readr::col_character(),
    `Number of patients for PPPW`                                                                                = readr::col_double(),
    `Percentage of Prevalent Patients Waitlisted`                                                                = readr::col_double(),
    `95% C.I. (upper limit) for PPPW`                                                                            = readr::col_double(),
    `95% C.I. (lower limit) for PPPW`                                                                            = readr::col_double(),
    `SEDR Date`                                                                                                  = readr::col_character(),
    `SEDR category text`                                                                                         = readr::col_character(),
    `Emergency Department Encounter data availability Code`                                                      = readr::col_character(),
    `Number of patients included in SEDR summary`                                                                = readr::col_double(),
    `Standardized ED visits ratio (Facility)`                                                                    = readr::col_double(),
    `SEDR: Upper Confidence Limit (97.5%)`                                                                       = readr::col_double(),
    `SEDR: Lower Confidence Limit (2.5%)`                                                                        = readr::col_double(),
    `ED30 Date`                                                                                                  = readr::col_character(),
    `ED30 Category text`                                                                                         = readr::col_character(),
    `Emergency Department Encounter Ratio Occurring within 30 Days of Hospital Discharge data availability Code` = readr::col_character(),
    `Number of hospitalizations included in ED30 summary`                                                        = readr::col_double(),
    `Standardized ED visits within 30 days of hospital discharge ratio (Facility)`                               = readr::col_double(),
    `ED30: Upper Confidence Limit (97.5%)`                                                                       = readr::col_double(),
    `ED30: Lower Confidence Limit (2.5%)`                                                                        = readr::col_double(),
    `YEARS Modality Switch BASED UPON`                                                                           = readr::col_character(),
    `SMoSR: Classification Category (FACILITY)`                                                                  = readr::col_character(),
    `Modality Switch Data Availability Code`                                                                     = readr::col_character(),
    `SMoSR: Number of Eligible patients (FACILITY)`                                                              = readr::col_double(),
    `SMoSR: Standardized Modality Switch Ratio (FACILITY)`                                                       = readr::col_double(),
    `SMoSR: Upper Confidence Limit (FACILITY)`                                                                   = readr::col_double(),
    `SMoSR: Lower Confidence Limit (FACILITY)`                                                                   = readr::col_double(),
    `SIR Date`                                                                                                   = readr::col_character(),
    `Patient Infection category text`                                                                            = readr::col_character(),
    `Patient Infection Data Availability Code`                                                                   = readr::col_character(),
    `Standard Infection Ratio`                                                                                   = readr::col_double(),
    `SIR: Upper Confidence Limit (97.5%)`                                                                        = readr::col_double(),
    `SIR: Lower Confidence Limit (2.5%)`                                                                         = readr::col_double(),
    `Fistula Category Text`                                                                                      = readr::col_character(),
    `Fistula data availability code`                                                                             = readr::col_character(),
    `Number of Patients included in fistula summary`                                                             = readr::col_double(),
    `Fistula Rate (Facility)`                                                                                    = readr::col_double(),
    `Fistula Rate: Upper Confidence Limit (97.5%)`                                                               = readr::col_double(),
    `Fistula Rate: Lower Confidence Limit (2.5%)`                                                                = readr::col_double(),
    `HCP Vaccination Data Collection Dates`                                                                      = readr::col_character(),
    `HCP Vaccination Data Availability Code`                                                                     = readr::col_character(),
    `Healthcare worker COVID-19 vaccination adherence percentage`                                                = readr::col_double(),
    `Adult HD Kt/V data availability code`                                                                       = readr::col_character(),
    `Number of adult HD patients with KT/V data`                                                                 = readr::col_double(),
    `Number of adult HD patient-months with Kt/V data`                                                           = readr::col_double(),
    `Percent of Adult HD patients with Kt/V > = 1.2`                                                             = readr::col_double(),
    `Adult PD Kt/V data availability code`                                                                       = readr::col_character(),
    `Number of adult PD patients with KT/V data`                                                                 = readr::col_double(),
    `Number of adult PD patient-months with Kt/V data`                                                           = readr::col_double(),
    `Percentage of Adult PD PTS with Kt/V > = 1.7`                                                               = readr::col_double(),
    `Pediatric HD Kt/V Data Availability Code`                                                                   = readr::col_character(),
    `Number of pediatric HD patients with Kt/V data`                                                             = readr::col_double(),
    `Number of pediatric HD patient-months with KT/V data`                                                       = readr::col_double(),
    `Percentage of Pediatric HD patients with Kt/V > = 1.2`                                                      = readr::col_double(),
    `Pediatric PD Kt/V Data Availability Code`                                                                   = readr::col_character(),
    `Number of pediatric PD patients with Kt/V data`                                                             = readr::col_double(),
    `Number of pediatric PD patient-months with KT/V data`                                                       = readr::col_double(),
    `Percentage of pediatric PD patients with Kt/V> =1.8`                                                        = readr::col_double(),
    `Percentage of Medicare patients with Hgb<10 g/dL`                                                           = readr::col_double(),
    `HGB<10 data availability code`                                                                              = readr::col_character(),
    `Percentage of Medicare patients with Hgb>12 g/dL`                                                           = readr::col_double(),
    `Hgb > 12 data availability code`                                                                            = readr::col_character(),
    `Number of Dialysis Patients with Hgb data`                                                                  = readr::col_double(),
    `Hypercalcemia Data Availability Code`                                                                       = readr::col_character(),
    `Number of patients in hypercalcemia summary`                                                                = readr::col_double(),
    `Number of patient-months in hypercalcemia summary`                                                          = readr::col_double(),
    `Percentage of Adult patients with hypercalcemia (serum calcium greater than 10.2 mg/dL)`                    = readr::col_double(),
    `Serum phosphorus Data Availability Code`                                                                    = readr::col_character(),
    `Number of patients in Serum phosphorus summary`                                                             = readr::col_double(),
    `Number of patient-months in Serum phosphorus summary`                                                       = readr::col_double(),
    `Percentage of Adult patients with serum phosphorus less than 3.5 mg/dL`                                     = readr::col_double(),
    `Percentage of Adult patients with serum phosphorus between 3.5-4.5 mg/dL`                                   = readr::col_double(),
    `Percentage of Adult patients with serum phosphorus between 4.6-5.5 mg/dL`                                   = readr::col_double(),
    `Percentage of Adult patients with serum phosphorus between 5.6-7.0 mg/dL`                                   = readr::col_double(),
    `Percentage of Adult patients with serum phosphorus greater than 7.0 mg/dL`                                  = readr::col_double(),
    `Long term catheter Data Availability Code`                                                                  = readr::col_character(),
    `Number of patients in long term catheter summary`                                                           = readr::col_double(),
    `Number of patient months in long term catheter summary`                                                     = readr::col_double(),
    `Percentage of Adult patients with long term catheter in use`                                                = readr::col_double(),
    `nPCR Data Availability Code`                                                                                = readr::col_character(),
    `Number of patients in nPCR summary`                                                                         = readr::col_double(),
    `Number of patient-months in nPCR summary`                                                                   = readr::col_double(),
    `Percentage of pediatric HD patients with nPCR`                                                              = readr::col_double()
  )) |>
  janitor::clean_names() |>
  collapse::mtt(
    cert_year = substr(certification_date, 6, 9) |> as.integer(),
    address = providertwo:::make_address(address_line_1, address_line_2),
    chain_owned = cheapr::val_match(chain_owned, "Yes" ~ 1L, "No" ~ 0L, .default = NA_integer_),
    profit_non = cheapr::val_match(profit_or_non_profit, "Non-profit" ~ "N", "Profit" ~ "P", .default = NA_character_),
    dial_stations = as.integer(number_of_dialysis_stations)
    ) |>
  collapse::slt(
    ccn = cms_certification_number_ccn,
    facility_name,
    address,
    city = city_town,
    state,
    zip = zip_code,
    county = county_parish,
    profit_non,
    chain_owned,
    chain_name = chain_organization,
    dial_stations,
    cert_year)

pin_update(
  esrd,
  name = "dialysis_facility",
  title = "Dialysis Facilities",
  description = "Dialysis Facility - Listing by Facility 2025")
