## code to prepare `state_data` dataset goes here

ccn_state_codes <- fastplyr::new_tbl(
  state_code = c(
    AZ = "00",
    AL = "01",
    AK = "02",
    AZ = "03",
    AR = "04",
    CA = "05",
    CO = "06",
    CT = "07",
    DE = "08",
    DC = "09",
    FL = "10",
    GA = "11",
    HI = "12",
    ID = "13",
    IL = "14",
    IN = "15",
    IA = "16",
    KS = "17",
    KY = "18",
    LA = "19",
    ME = "20",
    MD = "21",
    MA = "22",
    MI = "23",
    MN = "24",
    MS = "25",
    MO = "26",
    MT = "27",
    NE = "28",
    NV = "29",
    NH = "30",
    NJ = "31",
    NM = "32",
    NY = "33",
    NC = "34",
    ND = "35",
    OH = "36",
    OK = "37",
    OR = "38",
    PA = "39",
    PR = "40",
    RI = "41",
    SC = "42",
    SD = "43",
    TN = "44",
    TX = "45",
    UT = "46",
    VT = "47",
    VI = "48",
    VA = "49",
    WA = "50",
    WV = "51",
    WI = "52",
    WY = "53",
    ID = "54",
    CA = "55",
    CN = "56",
    NY = "57",
    WV = "58",
    MX = "59",
    AS = "64",
    GU = "65",
    CNMI = "66",
    TX = "67",
    FL = "68",
    FL = "69",
    KS = "70",
    LA = "71",
    OH = "72",
    PA = "73",
    TX = "74",
    CA = "75",
    IA = "76",
    MN = "77",
    IL = "78",
    MO = "79",
    MD = "80",
    CT = "81",
    MA = "82",
    NJ = "83",
    PR = "84",
    GA = "85",
    NC = "86",
    SC = "87",
    TN = "88",
    AR = "89",
    OK = "90",
    CO = "91",
    CA = "92",
    OR = "93",
    WA = "94",
    LA = "95",
    NM = "96",
    TX = "97",
    FC = "99",
    CA = "A0",
    CA = "A1",
    FL = "A2",
    LA = "A3",
    MI = "A4",
    MS = "A5",
    OH = "A6",
    PA = "A7",
    TN = "A8",
    TX = "A9",
    KY = "B0",
    WV = "B1",
    CA = "B2"
  ),
  state_abbr = c(
    "AZ", "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI",
    "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS",
    "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR",
    "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV",
    "WI", "WY", "ID", "CA", "CN", "NY", "WV", "MX", "AS", "GU", "CNMI", "TX",
    "FL", "FL", "KS", "LA", "OH", "PA", "TX", "CA", "IA", "MN", "IL", "MO", "MD",
    "CT", "MA", "NJ", "PR", "GA", "NC", "SC", "TN", "AR", "OK", "CO", "CA", "OR",
    "WA", "LA", "NM", "TX", "FC", "CA", "CA", "FL", "LA", "MI", "MS", "OH", "PA",
    "TN", "TX", "KY", "WV", "CA"
  ),
  state_name = c(
    "Arizona", "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida",
    "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
    "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan",
    "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina",
    "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Puerto Rico",
    "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas",
    "Utah", "Vermont", "Virgin Islands", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming", "Idaho", "California", "Canada",
    "New York", "West Virginia", "Mexico", "American Samoa", "Guam",
    "Commonwealth of the Northern Marianas Islands", "Texas", "Florida",
    "Florida", "Kansas", "Louisiana", "Ohio", "Pennsylvania", "Texas",
    "California", "Iowa", "Minnesota", "Illinois", "Missouri", "Maryland",
    "Connecticut", "Massachusetts", "New Jersey", "Puerto Rico", "Georgia",
    "North Carolina", "South Carolina", "Tennessee", "Arkansas", "Oklahoma",
    "Colorado", "California", "Oregon", "Washington", "Louisiana", "New Mexico",
    "Texas", "Foreign Countries (exceptions: Canada and Mexico)", "California",
    "California", "Florida", "Louisiana", "Michigan", "Mississippi", "Ohio",
    "Pennsylvania", "Tennessee", "Texas", "Kentucky", "West Virginia",
    "California"
  ),
)

usethis::use_data(ccn_state_codes, overwrite = TRUE)
