regions <- tibble::tribble(
  ~ro , ~region       , ~state , ~off          , ~office         ,
   0L , NA_character_ , "CN"   , NA_character_ , NA_character_   ,
   0L , NA_character_ , "FC"   , NA_character_ , NA_character_   ,
   0L , NA_character_ , "MX"   , NA_character_ , NA_character_   ,
   1L , "I"           , "CT"   , "BOS"         , "Boston"        ,
   1L , "I"           , "MA"   , "BOS"         , "Boston"        ,
   1L , "I"           , "ME"   , "BOS"         , "Boston"        ,
   1L , "I"           , "NH"   , "BOS"         , "Boston"        ,
   1L , "I"           , "RI"   , "BOS"         , "Boston"        ,
   1L , "I"           , "VT"   , "BOS"         , "Boston"        ,
   2L , "II"          , "NJ"   , "NYC"         , "New York City" ,
   2L , "II"          , "NY"   , "NYC"         , "New York City" ,
   2L , "II"          , "PR"   , "NYC"         , "New York City" ,
   2L , "II"          , "VI"   , "NYC"         , "New York City" ,
   3L , "III"         , "DC"   , "PHL"         , "Philadelphia"  ,
   3L , "III"         , "DE"   , "PHL"         , "Philadelphia"  ,
   3L , "III"         , "MD"   , "PHL"         , "Philadelphia"  ,
   3L , "III"         , "PA"   , "PHL"         , "Philadelphia"  ,
   3L , "III"         , "VA"   , "PHL"         , "Philadelphia"  ,
   3L , "III"         , "WV"   , "PHL"         , "Philadelphia"  ,
   4L , "IV"          , "AL"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "FL"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "GA"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "KY"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "MS"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "NC"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "SC"   , "ATL"         , "Atlanta"       ,
   4L , "IV"          , "TN"   , "ATL"         , "Atlanta"       ,
   5L , "V"           , "IL"   , "CHI"         , "Chicago"       ,
   5L , "V"           , "IN"   , "CHI"         , "Chicago"       ,
   5L , "V"           , "MI"   , "CHI"         , "Chicago"       ,
   5L , "V"           , "MN"   , "CHI"         , "Chicago"       ,
   5L , "V"           , "OH"   , "CHI"         , "Chicago"       ,
   5L , "V"           , "WI"   , "CHI"         , "Chicago"       ,
   6L , "VI"          , "AR"   , "DAL"         , "Dallas"        ,
   6L , "VI"          , "LA"   , "DAL"         , "Dallas"        ,
   6L , "VI"          , "NM"   , "DAL"         , "Dallas"        ,
   6L , "VI"          , "OK"   , "DAL"         , "Dallas"        ,
   6L , "VI"          , "TX"   , "DAL"         , "Dallas"        ,
   7L , "VII"         , "IA"   , "KC"          , "Kansas City"   ,
   7L , "VII"         , "KS"   , "KC"          , "Kansas City"   ,
   7L , "VII"         , "MO"   , "KC"          , "Kansas City"   ,
   7L , "VII"         , "NE"   , "KC"          , "Kansas City"   ,
   8L , "VIII"        , "CO"   , "DEN"         , "Denver"        ,
   8L , "VIII"        , "MT"   , "DEN"         , "Denver"        ,
   8L , "VIII"        , "ND"   , "DEN"         , "Denver"        ,
   8L , "VIII"        , "SD"   , "DEN"         , "Denver"        ,
   8L , "VIII"        , "UT"   , "DEN"         , "Denver"        ,
   8L , "VIII"        , "WY"   , "DEN"         , "Denver"        ,
   9L , "IX"          , "AS"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "AZ"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "CA"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "GU"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "HI"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "MP"   , "SF"          , "San Francisco" ,
   9L , "IX"          , "NV"   , "SF"          , "San Francisco" ,
  10L , "X"           , "AK"   , "SEA"         , "Seattle"       ,
  10L , "X"           , "ID"   , "SEA"         , "Seattle"       ,
  10L , "X"           , "OR"   , "SEA"         , "Seattle"       ,
  10L , "X"           , "WA"   , "SEA"         , "Seattle"       ,
)

usethis::use_data(regions, overwrite = TRUE)
# constructive::construct(constructive::opts_tbl_df("tribble"))
