states <- tibble::tribble(
  ~code , ~abbr , ~name                       ,
  "00"  , "AZ"  , "Arizona"                   ,
  "01"  , "AL"  , "Alabama"                   ,
  "02"  , "AK"  , "Alaska"                    ,
  "03"  , "AZ"  , "Arizona"                   ,
  "04"  , "AR"  , "Arkansas"                  ,
  "05"  , "CA"  , "California"                ,
  "06"  , "CO"  , "Colorado"                  ,
  "07"  , "CT"  , "Connecticut"               ,
  "08"  , "DE"  , "Delaware"                  ,
  "09"  , "DC"  , "District of Columbia"      ,
  "10"  , "FL"  , "Florida"                   ,
  "11"  , "GA"  , "Georgia"                   ,
  "12"  , "HI"  , "Hawaii"                    ,
  "13"  , "ID"  , "Idaho"                     ,
  "14"  , "IL"  , "Illinois"                  ,
  "15"  , "IN"  , "Indiana"                   ,
  "16"  , "IA"  , "Iowa"                      ,
  "17"  , "KS"  , "Kansas"                    ,
  "18"  , "KY"  , "Kentucky"                  ,
  "19"  , "LA"  , "Louisiana"                 ,
  "20"  , "ME"  , "Maine"                     ,
  "21"  , "MD"  , "Maryland"                  ,
  "22"  , "MA"  , "Massachusetts"             ,
  "23"  , "MI"  , "Michigan"                  ,
  "24"  , "MN"  , "Minnesota"                 ,
  "25"  , "MS"  , "Mississippi"               ,
  "26"  , "MO"  , "Missouri"                  ,
  "27"  , "MT"  , "Montana"                   ,
  "28"  , "NE"  , "Nebraska"                  ,
  "29"  , "NV"  , "Nevada"                    ,
  "30"  , "NH"  , "New Hampshire"             ,
  "31"  , "NJ"  , "New Jersey"                ,
  "32"  , "NM"  , "New Mexico"                ,
  "33"  , "NY"  , "New York"                  ,
  "34"  , "NC"  , "North Carolina"            ,
  "35"  , "ND"  , "North Dakota"              ,
  "36"  , "OH"  , "Ohio"                      ,
  "37"  , "OK"  , "Oklahoma"                  ,
  "38"  , "OR"  , "Oregon"                    ,
  "39"  , "PA"  , "Pennsylvania"              ,
  "40"  , "PR"  , "Puerto Rico"               ,
  "41"  , "RI"  , "Rhode Island"              ,
  "42"  , "SC"  , "South Carolina"            ,
  "43"  , "SD"  , "South Dakota"              ,
  "44"  , "TN"  , "Tennessee"                 ,
  "45"  , "TX"  , "Texas"                     ,
  "46"  , "UT"  , "Utah"                      ,
  "47"  , "VT"  , "Vermont"                   ,
  "48"  , "VI"  , "Virgin Islands"            ,
  "49"  , "VA"  , "Virginia"                  ,
  "50"  , "WA"  , "Washington"                ,
  "51"  , "WV"  , "West Virginia"             ,
  "52"  , "WI"  , "Wisconsin"                 ,
  "53"  , "WY"  , "Wyoming"                   ,
  "54"  , "ID"  , "Idaho"                     ,
  "55"  , "CA"  , "California"                ,
  "56"  , "CN"  , "Canada"                    ,
  "57"  , "NY"  , "New York"                  ,
  "58"  , "WV"  , "West Virginia"             ,
  "59"  , "MX"  , "Mexico"                    ,
  "64"  , "AS"  , "American Samoa"            ,
  "65"  , "GU"  , "Guam"                      ,
  # "66"  , "CNMI" , "Commonwealth of the Northern Marianas Islands" ,
  "66"  , "MP"  , "Northern Marianas Islands" ,
  "67"  , "TX"  , "Texas"                     ,
  "68"  , "FL"  , "Florida"                   ,
  "69"  , "FL"  , "Florida"                   ,
  "70"  , "KS"  , "Kansas"                    ,
  "71"  , "LA"  , "Louisiana"                 ,
  "72"  , "OH"  , "Ohio"                      ,
  "73"  , "PA"  , "Pennsylvania"              ,
  "74"  , "TX"  , "Texas"                     ,
  "75"  , "CA"  , "California"                ,
  "76"  , "IA"  , "Iowa"                      ,
  "77"  , "MN"  , "Minnesota"                 ,
  "78"  , "IL"  , "Illinois"                  ,
  "79"  , "MO"  , "Missouri"                  ,
  "80"  , "MD"  , "Maryland"                  ,
  "81"  , "CT"  , "Connecticut"               ,
  "82"  , "MA"  , "Massachusetts"             ,
  "83"  , "NJ"  , "New Jersey"                ,
  "84"  , "PR"  , "Puerto Rico"               ,
  "85"  , "GA"  , "Georgia"                   ,
  "86"  , "NC"  , "North Carolina"            ,
  "87"  , "SC"  , "South Carolina"            ,
  "88"  , "TN"  , "Tennessee"                 ,
  "89"  , "AR"  , "Arkansas"                  ,
  "90"  , "OK"  , "Oklahoma"                  ,
  "91"  , "CO"  , "Colorado"                  ,
  "92"  , "CA"  , "California"                ,
  "93"  , "OR"  , "Oregon"                    ,
  "94"  , "WA"  , "Washington"                ,
  "95"  , "LA"  , "Louisiana"                 ,
  "96"  , "NM"  , "New Mexico"                ,
  "97"  , "TX"  , "Texas"                     ,
  "99"  , "FC"  , "Foreign Country"           ,
  "A0"  , "CA"  , "California"                ,
  "A1"  , "CA"  , "California"                ,
  "A2"  , "FL"  , "Florida"                   ,
  "A3"  , "LA"  , "Louisiana"                 ,
  "A4"  , "MI"  , "Michigan"                  ,
  "A5"  , "MS"  , "Mississippi"               ,
  "A6"  , "OH"  , "Ohio"                      ,
  "A7"  , "PA"  , "Pennsylvania"              ,
  "A8"  , "TN"  , "Tennessee"                 ,
  "A9"  , "TX"  , "Texas"                     ,
  "B0"  , "KY"  , "Kentucky"                  ,
  "B1"  , "WV"  , "West Virginia"             ,
  "B2"  , "CA"  , "California"
)

usethis::use_data(states, overwrite = TRUE)

regions <- tibble::tribble(
  ~ro , ~region       , ~state , ~city           ,
   0L , NA_character_ , "CN"   , NA_character_   ,
   0L , NA_character_ , "FC"   , NA_character_   ,
   0L , NA_character_ , "MX"   , NA_character_   ,
   1L , "I"           , "CT"   , "Boston"        ,
   1L , "I"           , "MA"   , "Boston"        ,
   1L , "I"           , "ME"   , "Boston"        ,
   1L , "I"           , "NH"   , "Boston"        ,
   1L , "I"           , "RI"   , "Boston"        ,
   1L , "I"           , "VT"   , "Boston"        ,
   2L , "II"          , "NJ"   , "New York"      ,
   2L , "II"          , "NY"   , "New York"      ,
   2L , "II"          , "PR"   , "New York"      ,
   2L , "II"          , "VI"   , "New York"      ,
   3L , "III"         , "DC"   , "Philadelphia"  ,
   3L , "III"         , "DE"   , "Philadelphia"  ,
   3L , "III"         , "MD"   , "Philadelphia"  ,
   3L , "III"         , "PA"   , "Philadelphia"  ,
   3L , "III"         , "VA"   , "Philadelphia"  ,
   3L , "III"         , "WV"   , "Philadelphia"  ,
   4L , "IV"          , "AL"   , "Atlanta"       ,
   4L , "IV"          , "FL"   , "Atlanta"       ,
   4L , "IV"          , "GA"   , "Atlanta"       ,
   4L , "IV"          , "KY"   , "Atlanta"       ,
   4L , "IV"          , "MS"   , "Atlanta"       ,
   4L , "IV"          , "NC"   , "Atlanta"       ,
   4L , "IV"          , "SC"   , "Atlanta"       ,
   4L , "IV"          , "TN"   , "Atlanta"       ,
   5L , "V"           , "IL"   , "Chicago"       ,
   5L , "V"           , "IN"   , "Chicago"       ,
   5L , "V"           , "MI"   , "Chicago"       ,
   5L , "V"           , "MN"   , "Chicago"       ,
   5L , "V"           , "OH"   , "Chicago"       ,
   5L , "V"           , "WI"   , "Chicago"       ,
   6L , "VI"          , "AR"   , "Dallas"        ,
   6L , "VI"          , "LA"   , "Dallas"        ,
   6L , "VI"          , "NM"   , "Dallas"        ,
   6L , "VI"          , "OK"   , "Dallas"        ,
   6L , "VI"          , "TX"   , "Dallas"        ,
   7L , "VII"         , "IA"   , "Kansas City"   ,
   7L , "VII"         , "KS"   , "Kansas City"   ,
   7L , "VII"         , "MO"   , "Kansas City"   ,
   7L , "VII"         , "NE"   , "Kansas City"   ,
   8L , "VIII"        , "CO"   , "Denver"        ,
   8L , "VIII"        , "MT"   , "Denver"        ,
   8L , "VIII"        , "ND"   , "Denver"        ,
   8L , "VIII"        , "SD"   , "Denver"        ,
   8L , "VIII"        , "UT"   , "Denver"        ,
   8L , "VIII"        , "WY"   , "Denver"        ,
   9L , "IX"          , "AS"   , "San Francisco" ,
   9L , "IX"          , "AZ"   , "San Francisco" ,
   9L , "IX"          , "CA"   , "San Francisco" ,
   9L , "IX"          , "GU"   , "San Francisco" ,
   9L , "IX"          , "HI"   , "San Francisco" ,
   9L , "IX"          , "MP"   , "San Francisco" ,
   9L , "IX"          , "NV"   , "San Francisco" ,
  10L , "X"           , "AK"   , "Seattle"       ,
  10L , "X"           , "ID"   , "Seattle"       ,
  10L , "X"           , "OR"   , "Seattle"       ,
  10L , "X"           , "WA"   , "Seattle"       ,
)

usethis::use_data(regions, overwrite = TRUE)

# constructive::construct(constructive::opts_tbl_df("tribble"))
