STATE_CODE_LIST <- list(
  "Arizona"                                           = c("00", "03"),
  "Alabama"                                           = c("01"),
  "Alaska"                                            = c("02"),
  "Arkansas"                                          = c("04", "89"),
  "Colorado"                                          = c("06", "91"),
  "New Hampshire"                                     = c("30"),
  "New Jersey"                                        = c("31", "83"),
  "New Mexico"                                        = c("32", "96"),
  "New York"                                          = c("33", "57"),
  "California"                                        = c("05", "55", "75", "92", "A0", "A1", "B2"),
  "North Carolina"                                    = c("34", "86"),
  "North Dakota"                                      = c("35"),
  "Connecticut"                                       = c("07", "81"),
  "Ohio"                                              = c("36", "72", "A6"),
  "Delaware"                                          = c("08"),
  "Oklahoma"                                          = c("37", "90"),
  "District of Columbia"                              = c("09"),
  "Oregon"                                            = c("38", "93"),
  "Florida"                                           = c("10", "68", "69", "A2"),
  "Pennsylvania"                                      = c("39", "73", "A7"),
  "Georgia"                                           = c("11", "85"),
  "Puerto Rico"                                       = c("40", "84"),
  "Hawaii"                                            = c("12"),
  "Rhode Island"                                      = c("41"),
  "Idaho"                                             = c("13", "54"),
  "South Carolina"                                    = c("42", "87"),
  "Illinois"                                          = c("14", "78"),
  "South Dakota"                                      = c("43"),
  "Indiana"                                           = c("15"),
  "Tennessee"                                         = c("44", "88", "A8"),
  "Iowa"                                              = c("16", "76"),
  "Texas"                                             = c("45", "67", "74", "97", "A9"),
  "Kansas"                                            = c("17", "70"),
  "Utah"                                              = c("46"),
  "Kentucky"                                          = c("18", "B0"),
  "Vermont"                                           = c("47"),
  "Louisiana"                                         = c("19", "71", "95", "A3"),
  "Virgin Islands"                                    = c("48"),
  "Maine"                                             = c("20"),
  "Virginia"                                          = c("49"),
  "Maryland"                                          = c("21", "80"),
  "Washington"                                        = c("50", "94"),
  "Massachusetts"                                     = c("22", "82"),
  "West Virginia"                                     = c("51", "58", "B1"),
  "Michigan"                                          = c("23", "A4"),
  "Wisconsin"                                         = c("52"),
  "Minnesota"                                         = c("24", "77"),
  "Wyoming"                                           = c("53"),
  "Mississippi"                                       = c("25", "A5"),
  "Canada"                                            = c("56"),
  "Missouri"                                          = c("26", "79"),
  "Mexico"                                            = c("59"),
  "Montana"                                           = c("27"),
  "American Samoa"                                    = c("64"),
  "Nebraska"                                          = c("28"),
  "Guam"                                              = c("65"),
  "Nevada"                                            = c("29"),
  "Commonwealth of the Northern Marianas Islands"     = c("66"),
  "Foreign Countries (exceptions: Canada and Mexico)" = c("99")
)

STATE_NAME <- c(
  state.name,
  "District of Columbia",
  "Puerto Rico",
  "Virgin Islands",
  "Canada",
  "Mexico",
  "American Samoa",
  "Guam",
  "Commonwealth of the Northern Marianas Islands",
  "Foreign Countries (exceptions: Canada and Mexico)"
)

STATE_ABBR <- c(state.abb, "DC", "PR", "VI", "CN", "MX", "AS", "GU", "CNMI", "FC")

STATE_NAME_to_STATE_ABBR <- rlang::set_names(STATE_NAME, STATE_ABBR)
