# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <decode_six_medicare>
  # <decode_six_medicare_organ>
  # <decode_six_medicaid_only>
  # <decode_six_ipps_excluded>
  # <decode_six_emergency>
  # <decode_ten_supplier>
  "ccn",
  # <decode_ten_supplier>
  "cnn",
  # <decode_state>
  "code",
  # <make_switch>
  "constant",
  # <make_switch>
  "field",
  NULL
))
