#' @noRd
#' @autoglobal
STATE_CODES = tibble::tribble(~ from, ~ to,
  c("00", "03"),                               "Arizona",
  c("01"),                                     "Alabama",
  c("02"),                                     "Alaska",
  c("04", "89"),                               "Arkansas",
  c("06", "91"),                               "Colorado",
  c("30"),                                     "New Hampshire",
  c("31", "83"),                               "New Jersey",
  c("32", "96"),                               "New Mexico",
  c("33", "57"),                               "New York",
  c("05", "55", "75", "92", "A0", "A1", "B2"), "California",
  c("34", "86"), "North Carolina",
  c("35"), "North Dakota",
  c("07", "81"), "Connecticut",
  c("36", "72", "A6"), "Ohio",
  c("08"), "Delaware",
  c("37", "90"), "Oklahoma",
  c("09"), "District of Columbia",
  c("38", "93"), "Oregon",
  c("10", "68", "69", "A2"), "Florida",
  c("39", "73", "A7"), "Pennsylvania",
  c("11", "85"), "Georgia",
  c("40", "84"), "Puerto Rico",
  c("12"), "Hawaii",
  c("41"), "Rhode Island",
  c("13", "54"), "Idaho",
  c("42", "87"), "South Carolina",
  c("14", "78"), "Illinois",
  c("43"), "South Dakota",
  c("15"), "Indiana",
  c("44", "88", "A8"), "Tennessee",
  c("16", "76"), "Iowa",
  c("45", "67", "74", "97", "A9"), "Texas",
  c("17", "70"), "Kansas",
  c("46"), "Utah",
  c("18", "B0"), "Kentucky",
  c("47"), "Vermont",
  c("19", "71", "95", "A3"), "Louisiana",
  c("48"), "Virgin Islands",
  c("20"), "Maine",
  c("49"), "Virginia",
  c("21", "80"), "Maryland",
  c("50", "94"), "Washington",
  c("22", "82"), "Massachusetts",
  c("51", "58", "B1"), "West Virginia",
  c("23", "A4"), "Michigan",
  c("52"), "Wisconsin",
  c("24", "77"), "Minnesota",
  c("53"), "Wyoming",
  c("25", "A5"), "Mississippi",
  c("56"), "Canada",
  c("26", "79"), "Missouri",
  c("59"), "Mexico",
  c("27"), "Montana",
  c("64"), "American Samoa",
  c("28"), "Nebraska",
  c("65"), "Guam",
  c("29"), "Nevada",
  c("66"), "Commonwealth of the Northern Marianas Islands",
  c("99"), "Foreign Countries (exceptions: Canada and Mexico)"
)
